EventPoint.Samples.Web/ViewModels/EvalSessionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventPoint.Services.Api.Models;

namespace EventPoint.Samples.Web.ViewModels
{
    public class EvalSessionViewModel
    {
        public Topic Session { get; set; }
        public IntegratedSurveyModel Eval { get; set; }
    }
}

EventPoint.Samples.Web/ViewModels/SessionCatalogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventPoint.Services.Api.Models;

namespace EventPoint.Samples.Web.ViewModels
{
    public class SessionCatalogViewModel
    {
        public CategoryFilterViewModel SessionTypeFilter { get; set; }
        public CategoryFilterViewModel TrackFilter { get; set; }
        public CategoryFilterViewModel LevelFilter { get; set; }
        public CategoryFilterViewModel SpecialtyFilter { get; set; }
        public CategoryFilterViewModel AudienceFilter { get; set; }
        public string Keyword { get; set; }
        public List<SessionViewModel> Sessions { get; set; }
    }

    public class CategoryFilterViewModel
    {
        public string Label { get; set; }
        public List<Category> Items { get; set; }
        public string SelectedId { get; set; }
    }

    public class SessionViewModel
    {
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SessionType { get; set; }
        public string Track { get; set; }
        public string Level { get; set; }
        public string Specialty { get; set; }
        public string Audience { get; set; }
    }
}

EventPoint.Samples.Web/Controllers/EvalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EventPoint.Samples.Clients.Web.ViewModels;
using EventPoint.Services.Api.Models;

namespace EventPoint.Samples.Clients.Web.Controllers
{
    public class EvalController : Controller
    {
        // GET: Eval
        public async Task<ActionResult> Session(string id)
        {
            var client = Helper.ApiClient();
            var registrantKey = Helper.RegistrantKey();

            var session = await client.GetTopicAsync(id);
            
            var eval = await client.GetEvalForSessionAsync(registrantKey, id);
            var model = new EvalSessionViewModel
            {
                Session = session,
                Eval = eval
            };
            return View(model);
        }
    }
}

EventPoint.Samples.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventPoint.Samples.Clients.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EventPoint.Samples.Web/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using EventPoint.Samples.Web.ViewModels;
using EventPoint.Services.Api.Models;

namespace EventPoint.Samples.Web.Controllers
{
    public class SessionController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Catalog(string keyword = "", string fSessionType = "", string fTrack = "", string fLevel = "", string fSpecialty = "", string fAudience = "")
        {           
            var client = await Helper.GetApiClient();
            var topics = await client.GetTopicsAsync();
            
            //filter sessions by category, if appropriate.  this is an AND filter.
            if (!String.IsNullOrEmpty(fSessionType))
            {
                topics = topics.Where(x => x.CategoryIds.Contains(fSessionType)).ToList();
            }
            if (!String.IsNullOrEmpty(fTrack))
            {
                topics = topics.Where(x => x.CategoryIds.Contains(fTrack)).ToList();
            }
            if (!String.IsNullOrEmpty(fLevel))
            {
                topics = topics.Where(x => x.CategoryIds.Contains(fLevel)).ToList();
            }
            if (!String.IsNullOrEmpty(fSpecialty))
            {
                topics = topics.Where(x => x.CategoryIds.Contains(fSpecialty)).ToList();
            }
            if (!String.IsNullOrEmpty(fAudience))
            {
                topics = topics.Where(x => x.CategoryIds.Contains(fAudience)).ToList();
            }

            if(!String.IsNullOrEmpty(keyword))
            {
                topics = topics.Where(x => x.Title.ToLower().Contains(keyword.ToLower()) || x.Description.ToLower().Contains(keyword.ToLower())).ToList();
            }

            //join topics against the Session Type category so you can display the value along with other session details
            var sessiontypes = await client.GetChildCategoriesAsync("session type");
            var tracks = await client.GetChildCategoriesAsync("track");
            var levels = await client.GetChildCategoriesAsync("level");
            var specialties = await client.GetChildCategoriesAsync("specialty/vertical");
            var audiences = await client.GetChildCategoriesAsync("target audience");

            var sessions = from topic in topics
                           select new SessionViewModel
                           {
                               Code = topic.Code,
                               Title = topic.Title,
                               Description = topic.Description,
                               SessionType = String.Join(", ", audiences.Where(x => topic.CategoryIds.Contains(x.Id)).Select(x => x.Name).ToList()),
                               Track = String.Join(", ", tracks.Where(x => topic.CategoryIds.Contains(x.Id)).Select(x => x.Name).ToList()),
                               Level = String.Join(", ", levels.Where(x => topic.CategoryIds.Contains(x.Id)).Select(x => x.Name).ToList()),
                               Specialty = String.Join(", ", specialties.Where(x => topic.CategoryIds.Contains(x.Id)).Select(x => x.Name).ToList()),
                               Audience = String.Join(", ", audiences.Where(x => topic.CategoryIds.Contains(x.Id)).Select(x => x.Name).ToList())
                           };
            

            var sessionTypeFilter = await GetCategoryFilter("Session Type", fSessionType);
            var trackFilter = await GetCategoryFilter("Track", fTrack);
            var levelFilter = await GetCategoryFilter("Level", fLevel);
            var specialtyFilter = await GetCategoryFilter("Specialty/Vertical", fLevel);
            var audienceFilter = await GetCategoryFilter("Target Audience", fLevel);

            var model = new SessionCatalogViewModel
            {
                SessionTypeFilter = sessionTypeFilter,
                TrackFilter = trackFilter,
                LevelFilter = levelFilter,
                SpecialtyFilter = specialtyFilter,
                AudienceFilter = audienceFilter,
                Sessions = sessions.OrderBy(x => x.Code).Take(20).ToList()
            };

            return View(model);
        }

        private async Task<CategoryFilterViewModel> GetCategoryFilter(string name, string selected)
        {
            var client = await Helper.GetApiClient();
            var categories = await client.GetChildCategoriesAsync(name);
            categories.Add(new Category { Id = "", Name = "--" });
            return new CategoryFilterViewModel
            {
                Label = name,
                Items = categories.OrderBy(x => x.Name).ToList(),
                SelectedId = selected
            };
        }

    }
}

EventPoint.Samples.Web/Views/Eval/Session.cshtml
@model EventPoint.Samples.Web.ViewModels.EvalSessionViewModel
@{
    ViewBag.Title = "Session Eval";
}

<style>
    .eval_group
    {
     
    }
    .eval_group_header
    {
        background-color:lightgrey;
        padding:5px;
        border:1px solid black;
        font-size:larger;
        font-weight:bold;
    }

    .eval_question
    {
        margin-bottom:30px;
    }

    .eval_question_text
    {
        font-weight:bold;
    }

    .eval_answers
    {
    }

    

    .eval_rbl_4_answers
    {
        width:25%;
        float:left;
    }

    .eval_rbl_5_answers
    {
        width:20%;
        float:left;
    }

    .eval_rbl_6_answers
    {
        width:16%;
        float:left;
    }

    .eval_rbl_9_answers
    {
        width:11%;
        float:left;;
    }

</style>

<div class="col-md-12">
    <div class="h2">Session Eval</div>
</div>
<div class="col-md-12" style="background:beige; border:1px solid gray; padding:10px; margin-bottom:25px;">
    <div>Session Code: @Model.Session.Code</div>
    <div>Session Title: @Model.Session.Title</div>
    <div>Eval Name: @Model.Eval.Code</div>
</div>


<!--render the form-->
@foreach (var group in Model.Eval.QuestionGroups.OrderBy(x => x.Order))
{
    <div class="col-md-12">
        <div class="eval_group">
            <div class="eval_group_header">@group.HeaderText</div>
        </div>
    </div>
    foreach(var question in group.Questions.OrderBy(x => x.Order))
    {
        <div class="col-md-12">  
            <div class="eval_question">
                <div class="eval_question_text">@question.Text</div>
                <div class="eval_answers">
                    @if(question.QuestionType == "1")
                    {
                        foreach (var answer in question.Answers)
                        {
                            <div><input type="checkbox" value="@answer.Id" />&nbsp;@answer.Text</div>
                        }
                    }
                    else if (question.QuestionType == "2" && group.Name == "Group05")
                    {
                        foreach (var answer in question.Answers)
                        {
                            <div class="eval_rbl_@(question.Answers.Count())_answers">
                                <div>@answer.Label &nbsp;</div>
                                <div><input type="radio" group="@question.Id" value="@answer.Id"  />&nbsp;@answer.Text</div>
                            </div>
                        }
                    }
                    else if (question.QuestionType == "2")
                    {
                        foreach (var answer in question.Answers)
                        {
                            <div class="eval_rbl_@(question.Answers.Count())_answers" style="text-align:center">
                                <div>@answer.Label &nbsp;</div>
                                <div><input type="radio" group="@question.Id" value="@answer.Id" /></div>
                            </div>
                        }
                    }
                    else if (question.QuestionType == "4")
                    {
                        <div>
                            <textarea class="form-control"></textarea>
                        </div>   
                    }
                </div>
            </div>
        </div>
    }
}

EventPoint.Samples.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EventPoint.Samples.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EventPoint.Samples.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="col-md-12">
    <div class="h2">Sample Web Home</div>
    @Html.ActionLink("Session Catalog", "Catalog", "Session")
</div>

EventPoint.Samples.Web/Views/Session/Catalog.cshtml
@model EventPoint.Samples.Web.ViewModels.SessionCatalogViewModel
@{
    ViewBag.Title = "Session Catalog";
}
<div class="col-md-6">
    @using (Html.BeginForm("Catalog", "Session", FormMethod.Get))
    {
        <div class="filterset">
            <div class="filterset__filter">
                <div class="filterset__filter__label">@Model.SessionTypeFilter.Label</div>
                <div class="filterset__filter__control">@Html.DropDownList("fSessionType", new SelectList(Model.SessionTypeFilter.Items, "Id", "Name", Model.SessionTypeFilter.SelectedId), new { @class = "form-control" })</div>
            </div>
            <div class="filterset__filter">
                <div class="filterset__filter__label">@Model.TrackFilter.Label</div>
                <div class="filterset__filter__control">@Html.DropDownList("fTrack", new SelectList(Model.TrackFilter.Items, "Id", "Name", Model.TrackFilter.SelectedId), new { @class = "form-control" })</div>
            </div>
            <div class="filterset__filter">
                <div class="filterset__filter__label">@Model.LevelFilter.Label</div>
                <div class="filterset__filter__control">@Html.DropDownList("fLevel", new SelectList(Model.LevelFilter.Items, "Id", "Name", Model.LevelFilter.SelectedId), new { @class = "form-control" })</div>
            </div>
            <div class="filterset__filter">
                <div class="filterset__filter__label">@Model.SpecialtyFilter.Label</div>
                <div class="filterset__filter__control">@Html.DropDownList("fSpecialty", new SelectList(Model.SpecialtyFilter.Items, "Id", "Name", Model.SpecialtyFilter.SelectedId), new { @class = "form-control" })</div>
            </div>
            <div class="filterset__filter">
                <div class="filterset__filter__label">@Model.AudienceFilter.Label</div>
                <div class="filterset__filter__control">@Html.DropDownList("fAudience", new SelectList(Model.AudienceFilter.Items, "Id", "Name", Model.AudienceFilter.SelectedId), new { @class = "form-control" })</div>
            </div>
            <div class="filterset__filter">
                <div class="filterset__filter__label"></div>
                <div class="filterset__filter__control"><input type="submit" value="Submit" class="form-control pull-right" style="width:100px;" /></div>
            </div>
        </div>       
    }
    <div class="sessionlist">
        @foreach (var session in Model.Sessions)
        {
            <div class="sessionlist__session">
                <div class="sessionlist__session__code">@session.Code</div>
                <div class="sessionlist__session__title">@session.Title</div>
                <div class="sessionlist__session__description">@session.Description</div>
                <div class="sessionlist__session__tag"><div class="sessionlist__session__tag__label">Session Type:</div> @session.SessionType</div>
                <div class="sessionlist__session__tag"><div class="sessionlist__session__tag__label">Track:</div> @session.Track</div>
                <div class="sessionlist__session__tag"><div class="sessionlist__session__tag__label">Level:</div> @session.Level</div>
                <div class="sessionlist__session__tag"><div class="sessionlist__session__tag__label">Specalty:</div> @session.Specialty</div>
                <div class="sessionlist__session__tag"><div class="sessionlist__session__tag__label">Audience:</div> @session.Audience</div>
            </div>
        }
    </div>
</div>

EventPoint.Samples.Web/Views/Session/Index.cshtml
@model EventPoint.Samples.Clients.Web.ViewModels.SessionIndexViewModel
@{
    ViewBag.Title = "Sessions";
}

<div class="col-md-12">
    <div class="h2">Sessions</div>
</div>
<div class="col-md-12">
    @foreach(var session in Model.Sessions)
    {
        <div style="margin-bottom:10px">
            <div>@session.Title</div>
            <div>@Html.ActionLink("View Eval", "Session", "Eval", new { id = @session.Id }, null)</div>
        </div>
    }
</div>

EventPoint.Samples.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/EventPoint/less")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EventPoint Sample Web", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Session Catalog", "Catalog", "Session")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>